- .editorconfig
- src/admin/admin_db.php
- src/startseite_l.php
- src/termine_l.php
- 404 for logged in (panini bildli)
- implode deprecated args order
- stricter MySQL
> Fix some errors

- src/fuer_einsteiger_l.php
- src/index.php
- src/karten_l.php
- take-screenshots.sh
SCREENSHOT_APPROVE={"karten":"all","fuer_einsteiger":"all"}
> Fix flaky tests.

- src/index.php
- src/menu.php
- src/styles.css
!!! This decreases the UX for users with IE !!!
> Less jitterish menu.

- src/galerie_r.php
> Fix photo counts for Galerie

- .github/workflows/ci-prod.yml
- .github/workflows/ci-test.yml
> Cache NPM dependencies in GitHub Actions

- src/index.js
- src/library/phpWebFileManager/start.php
- src/menu.php
- src/results/index.html
- src/results/index.js
- src/results/live_uploader/run.sh
- src/results/live_uploader/uploader/__init__.py
- src/results/live_uploader/uploader/__main__.py
- src/results/live_uploader/uploader/updater.py
- src/results/live_uploader/uploader/webui.py
- src/results/results.css
- src/results/results.js
- src/results/update.php
- src/styles.css
- src/trophy.php
- webpack.config.js
> Add results code

- src/fuer_einsteiger_l.php
- src/header.css
- src/header.js
- src/header.php
- src/icns/menu_close.svg
- src/icns/menu_hamburger.svg
- src/icns/olz_logo.svg
- src/index.css
- src/index.js
- src/index.php
- src/menu.css
- src/menu.php
- src/styles.css
- src/tools/dev-data/db_content.sql
- src/tools/dev-data/db_structure.sql
- tests/integration_tests/utils/adjust_for_pageshot.css
- tests/integration_tests/utils/screenshot.php
> Bessere Unterstützung für Mobilgeräte (responsive design)

- build-deployment.sh
- src/resultate/live_uploader/public_html/index.js
- src/resultate/live_uploader/uploader/updater.py
- src/resultate/results.js
- webpack.config.js
> Fix resultate

- src/tools/dev-data/db_content.sql
- src/tools/dev-data/db_structure.sql
- src/tools/dev_data.php
> Kaderblog-Eintrag mit Bildern & PDFs

- src/account.php
- src/account.scss
- src/bootstrap.scss
- src/header.php
- src/header.scss
- src/icns/user.svg
- src/index.js
- src/index.scss
> User account menu

- src/termine_l.php
- src/trophy_d.php
- tests/screenshot_tests/modules/login_logout.php
- tests/screenshot_tests/modules/profile.php
- tests/screenshot_tests/utils/adjust_for_pageshot.css
ausserdem Versuch, die unsteten Screenshots zu flicken
> Mapbox URLs aktualisieren

- .github/workflows/ci-prod.yml
- .github/workflows/ci-test.yml
- README.md
- deploy.sh
> Deploy script

- src/galerie_r.php
- tests/screenshot_tests/utils/hideFlaky.js
SCREENSHOT_APPROVE={"aktuell_new_edit-firefox":"all","forum_new_edit-firefox":"all","galerie_id_2-firefox.png":"all","galerie_new_edit-firefox":"all","galerie_new_finished-firefox":"all","galerie_new_preview-firefox":"all"}
> Auto-Korrektur deaktivieren bei Screenshot-Tests

- src/aktuell.php
- src/blog.php
- src/components/page/olz_header_bar/olz_header_bar.js
- src/config/init.php
- src/error.php
- src/fuer_einsteiger.php
- src/index.php
- src/karten.php
- src/kontakt.php
- src/material.php
- src/search.php
- src/service.php
- src/startseite.php
- src/trophy.php
- tests/screenshot_tests/utils/screenshot.php
> Set cookie only if required

- dev-server/config.template.php
- src/admin/admin_db.php
- src/admin/olz_functions.php
- src/aktuell_l.php
- src/aktuell_r.php
- src/blog_l.php
- src/config/date.php
- src/config/server.php
- src/forum_l.php
- src/galerie_l.php
- src/galerie_r.php
- src/ical.php
- src/results.php
- src/startseite_l.php
- src/termine_l.php
- src/termine_tools.php
- src/termine_tools_DEV.php
- src/tickers.php
- src/tools/dev-data/db_content.sql
- src/tools/dev-data/db_structure.sql
- src/utils/date/DateUtils.php
- src/zol/karten.php
- tests/integration_tests/document-root/config.template.php
- tests/screenshot_tests/modules/termine.php
> Use DateUtils everywhere

- src/sitemap.php
> Add sitemap

- src/api/endpoints/GetLogsEndpoint.php
- src/logs.php
- src/logs.scss
- src/logs.ts
> Improve logs

- src/components/page/olz_header/olz_header.php
> Improve canonical URL

- src/model/Aktuell.php
- src/model/AktuellRepository.php
- src/model/Galerie.php
- src/model/GalerieRepository.php
- src/model/index.php
- src/sitemap.php
> Add aktuell and galerie entries to sitemap

- src/scripts/file_tools.ts
> Move file_tools to TypeScript

- src/api/common/Endpoint.php
- src/tasks/common/BackgroundTask.php
- src/termine.php
- src/termine_l.php
- src/tools/dev-data/db_content.sql
- src/tools/dev-data/db_structure.sql
- src/utils/TermineUtils.php
- src/utils/env/EnvUtils.php
- tests/integration_tests/utils/TermineUtilsIntegrationTest.php
- tests/screenshot_tests/modules/index.php
- tests/screenshot_tests/modules/termine.php
- tests/unit_tests/utils/TermineUtilsTest.php
> Make termine filter deterministic

- src/trophy_d.php
SCREENSHOT_APPROVE={"trophy-firefox":"all"}
> Trophy update

- src/model/NotificationSubscription.php
- src/model/UserRepository.php
- src/tasks/SendDailyNotificationsTask.php
- tests/fake/FakeUserRepository.php
- tests/unit_tests/api/endpoints/ExecuteEmailReactionEndpointTest.php
- tests/unit_tests/news/endpoints/CreateNewsEndpointTest.php
- tests/unit_tests/tasks/SendDailyNotificationsTaskTest.php
> Fix config reminder generator

- src/components/notify/olz_email_card/olz_email_card.php
- src/components/notify/olz_email_card/olz_email_card.scss
- src/components/notify/olz_telegram_card/olz_telegram_card.php
- src/components/notify/olz_telegram_card/olz_telegram_card.scss
- src/service_l.php
- src/styles/styles.scss
> Fix service layout

- src/termine/termine_list.php
> Remove participant number from termine list

- src/admin/admin_db.php
- src/termine/termine_list.php
- src/utils/TermineUtils.php
- tests/unit_tests/utils/TermineUtilsTest.php
> Jahresprogramm, Weekends filter in Termine

- src/model/AuthRequestRepository.php
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
> Fix auth throttling

- src/api/OlzEndpoint.php
- src/api/endpoints/ResetPasswordEndpoint.php
- tests/unit_tests/api/endpoints/ResetPasswordEndpointTest.php
> Improve reCaptcha and logging for ResetPasswordEndpoint

- src/admin/admin_db.php
> Fix base64 encoded email

- src/resultate/results.css
- src/zimmerberg_ol/index.php
- src/zimmerberg_ol/index.ts
- src/zimmerberg_ol/styles.scss
- webpack.config.js
> Zimmerberg OL: Webpack

- _/karten_l.php
> Fix issue with account menu not opening on karten.php

- src/Apps/Oev/Endpoints/SearchTransportConnectionEndpoint.php
- src/Apps/Oev/Utils/TransportConnection.php
- src/Apps/Oev/Utils/TransportHalt.php
- src/Apps/Oev/Utils/TransportSection.php
- src/Apps/Oev/Utils/TransportSuggestion.php
- tests/UnitTests/Apps/Oev/Endpoints/SearchTransportConnectionEndpointTest.php
- tests/UnitTests/Apps/Oev/Endpoints/from_8502208_to_Flumserberg_Tannenheim_at_2021-10-01T13-15.json
- tests/UnitTests/Apps/Oev/Endpoints/from_8502208_to_Winterthur_at_2021-09-22T09-00.json
- tests/UnitTests/Apps/Oev/Endpoints/from_8503000_to_Flumserberg_Tannenheim_at_2021-10-01T13-15.json
- tests/UnitTests/Apps/Oev/Endpoints/from_8503009_to_Flumserberg_Tannenheim_at_2021-10-01T13-15.json
- tests/UnitTests/Apps/Oev/Endpoints/from_8503011_to_Flumserberg_Tannenheim_at_2021-10-01T13-15.json
- tests/UnitTests/Apps/Oev/Endpoints/from_8503096_to_Flumserberg_Tannenheim_at_2021-10-01T13-15.json
- tests/UnitTests/Apps/Oev/Endpoints/from_8503096_to_Winterthur_at_2021-09-22T09-00.json
- tests/UnitTests/Apps/Oev/Endpoints/from_8503097_to_Flumserberg_Tannenheim_at_2021-10-01T13-15.json
- tests/UnitTests/Apps/Oev/Endpoints/from_8503097_to_Winterthur_at_2021-09-22T09-00.json
- tests/UnitTests/Apps/Oev/Endpoints/from_8503200_to_Flumserberg_Tannenheim_at_2021-10-01T13-15.json
- tests/UnitTests/Apps/Oev/Endpoints/from_8503201_to_Flumserberg_Tannenheim_at_2021-10-01T13-15.json
- tests/UnitTests/Apps/Oev/Endpoints/from_8503203_to_Flumserberg_Tannenheim_at_2021-10-01T13-15.json
- tests/UnitTests/Apps/Oev/Endpoints/from_8503205_to_Flumserberg_Tannenheim_at_2021-10-01T13-15.json
- tests/UnitTests/Apps/Oev/Endpoints/from_8503206_to_Flumserberg_Tannenheim_at_2021-10-01T13-15.json
- tests/UnitTests/Apps/Oev/Endpoints/from_8503207_to_Flumserberg_Tannenheim_at_2021-10-01T13-15.json
- tests/UnitTests/Apps/Oev/Endpoints/from_8503207_to_Winterthur_at_2021-09-22T09-00.json
- tests/UnitTests/Apps/Oev/Utils/TransportConnectionTest.php
- tests/UnitTests/Apps/Oev/Utils/TransportHaltTest.php
> Fix öV App

- src/Apps/Oev/Components/OlzTransportConnectionSearch/OlzTransportConnectionSearch.tsx
- src/Apps/Oev/Components/OlzTransportConnectionView/OlzTransportConnectionView.tsx
- src/Apps/Oev/Endpoints/SearchTransportConnectionEndpoint.php
- tests/UnitTests/Apps/Oev/Endpoints/SearchTransportConnectionEndpointTest.php
- tests/UnitTests/Apps/Oev/Endpoints/from_8502208_to_Chur_at_2022-10-30T15-00.json
- tests/UnitTests/Apps/Oev/Endpoints/from_8503009_to_Chur_at_2022-10-30T15-00.json
- tests/UnitTests/Apps/Oev/Endpoints/from_8503010_to_Chur_at_2022-10-30T15-00.json
- tests/UnitTests/Apps/Oev/Endpoints/from_8503011_to_Chur_at_2022-10-30T15-00.json
- tests/UnitTests/Apps/Oev/Endpoints/from_8503096_to_Chur_at_2022-10-30T15-00.json
- tests/UnitTests/Apps/Oev/Endpoints/from_8503097_to_Chur_at_2022-10-30T15-00.json
- tests/UnitTests/Apps/Oev/Endpoints/from_8503204_to_Chur_at_2022-10-30T15-00.json
- tests/UnitTests/Apps/Oev/Endpoints/from_8503205_to_Chur_at_2022-10-30T15-00.json
- tests/UnitTests/Apps/Oev/Endpoints/from_8503207_to_Chur_at_2022-10-30T15-00.json
> Improve öV App, add bad test case

- .github/workflows/ci-prod.yml
- .github/workflows/ci-test.yml
- Deploy.php
- README.md
- composer.json
- composer.lock
> Add hosttech deployment

- _/datenschutz.php
- _/konto_passwort.php
- _/konto_passwort.ts
- src/Api/Endpoints/ResetPasswordEndpoint.php
- src/Api/Endpoints/SignUpWithPasswordEndpoint.php
- src/Api/client/generated_olz_api_types.ts
- src/Components/Auth/OlzResetPasswordModal/OlzResetPasswordModal.php
- src/Components/Auth/OlzResetPasswordModal/OlzResetPasswordModal.ts
- src/Components/Common/OlzDefaultForm/OlzDefaultForm.ts
- src/Utils/RecaptchaUtils.php
- src/Utils/WithUtilsTrait.php
- src/Utils/recaptchaUtils.ts
- tests/Fake/FakeRecaptchaUtils.php
- tests/IntegrationTests/Utils/RecaptchaUtilsIntegrationTest.php
- tests/UnitTests/Api/Endpoints/ResetPasswordEndpointTest.php
- tests/UnitTests/Api/Endpoints/SignUpWithPasswordEndpointTest.php
- tests/UnitTests/Utils/RecaptchaUtilsTest.php
- tests/screenshot_tests/modules/konto_passwort.php
> reCaptcha for sign-up

- src/News/Components/OlzNewsList/OlzNewsList.php
- src/News/Components/OlzNewsList/OlzNewsList.scss
- src/News/Components/OlzNewsList/OlzNewsList.ts
- src/News/Components/index.ts
> News: "Infinite scrolling"

- tests/Fake/FakeContext.ts
- tsconfig.json
> TypeScript: Enable strict property init

- src/News/Components/OlzEditNewsModal/OlzEditNewsModal.tsx
- src/News/Components/OlzNewsArticle/OlzNewsArticle.ts
> Improve edit news

- src/Startseite/Components/OlzWeeklyPictureTile/OlzWeeklyPictureTile.php
> Fix Bid der Woche for mobile

- src/News/Components/OlzNewsList/OlzNewsList.php
- src/News/Components/OlzNewsList/OlzNewsList.scss
> "No entries" for news

- _/email_reaktion.php
- _/konto_telegram.php
- _/profil.php
- _/webftp.php
- _/zol/zol_index.php
- src/Apps/Import/Components/OlzImport/OlzImport.php
- src/Apps/Logs/Components/OlzLogs/OlzLogs.php
- src/Apps/Newsletter/Components/OlzNewsletter/OlzNewsletter.php
> Replace session_start with session_start_if_cookie_set

- src/Fetchers/SolvFetcher.php
- src/Tasks/SyncSolvTask/SolvResultsSyncer.php
> Fix SOLV fetcher

- src/Components/Page/OlzMenu/OlzMenu.php
> Menu umstrukturieren

- _/startseite.php
- src/Api/Endpoints/OnDailyEndpoint.php
- src/Command/CleanTempDirectoryCommand.php
- src/Command/OnDailyCommand.php
- tests/UnitTests/Api/Endpoints/OnDailyEndpointTest.php
- tests/UnitTests/Command/CleanTempDirectoryCommandTest.php
- tests/UnitTests/Command/OnDailyCommandTest.php
> Migrate CleanTempDirectory Task -> Command

- src/Api/Endpoints/OnContinuouslyEndpoint.php
- src/Command/OnContinuouslyCommand.php
- src/Command/OnDailyCommand.php
- src/Command/SendDailyNotificationsCommand.php
- src/Command/SendDailyNotificationsCommand/DailySummaryGetter.php
- src/Command/SendDailyNotificationsCommand/DeadlineWarningGetter.php
- src/Command/SendDailyNotificationsCommand/EmailConfigurationReminderGetter.php
- src/Command/SendDailyNotificationsCommand/MonthlyPreviewGetter.php
- src/Command/SendDailyNotificationsCommand/Notification.php
- src/Command/SendDailyNotificationsCommand/TelegramConfigurationReminderGetter.php
- src/Command/SendDailyNotificationsCommand/WeeklyPreviewGetter.php
- src/Command/SendDailyNotificationsCommand/WeeklySummaryGetter.php
- tests/IntegrationTests/Tasks/SendDailyNotificationsTask/DailySummaryGetterIntegrationTest.php
- tests/IntegrationTests/Tasks/SendDailyNotificationsTask/DeadlineWarningGetterIntegrationTest.php
- tests/IntegrationTests/Tasks/SendDailyNotificationsTask/EmailConfigurationReminderGetterIntegrationTest.php
- tests/IntegrationTests/Tasks/SendDailyNotificationsTask/MonthlyPreviewGetterIntegrationTest.php
- tests/IntegrationTests/Tasks/SendDailyNotificationsTask/TelegramConfigurationReminderGetterIntegrationTest.php
- tests/IntegrationTests/Tasks/SendDailyNotificationsTask/WeeklyPreviewGetterIntegrationTest.php
- tests/IntegrationTests/Tasks/SendDailyNotificationsTask/WeeklySummaryGetterIntegrationTest.php
- tests/UnitTests/Api/Endpoints/OnContinuouslyEndpointTest.php
- tests/UnitTests/Command/OnContinuouslyCommandTest.php
- tests/UnitTests/Command/SendDailyNotificationsCommand/DailySummaryGetterTest.php
- tests/UnitTests/Command/SendDailyNotificationsCommand/DeadlineWarningGetterTest.php
- tests/UnitTests/Command/SendDailyNotificationsCommand/EmailConfigurationReminderGetterTest.php
- tests/UnitTests/Command/SendDailyNotificationsCommand/MonthlyPreviewGetterTest.php
- tests/UnitTests/Command/SendDailyNotificationsCommand/NotificationTest.php
- tests/UnitTests/Command/SendDailyNotificationsCommand/TelegramConfigurationReminderGetterTest.php
- tests/UnitTests/Command/SendDailyNotificationsCommand/WeeklyPreviewGetterTest.php
- tests/UnitTests/Command/SendDailyNotificationsCommand/WeeklySummaryGetterTest.php
- tests/UnitTests/Command/SendDailyNotificationsCommandTest.php
> Migrate SendDailyNotifications Task -> Command

- src/Apps/Commands/Endpoints/ExecuteCommandEndpoint.php
- src/Components/Common/OlzPostingListItem/OlzPostingListItem.php
- src/News/Components/OlzNewsArticle/OlzNewsArticle.php
- src/News/Components/OlzNewsDetail/OlzNewsDetail.php
- src/Termine/Components/OlzICal/OlzICal.php
- src/Termine/Components/OlzTerminDetail/OlzTerminDetail.php
- src/Termine/Components/OlzTermineList/OlzTermineList.php
- src/Termine/Components/OlzTermineSidebar/OlzTermineSidebar.php
- tests/SystemTests/StatusTest.php
> Fix execute command, $_DATE => $this->dateUtils()

- src/Apps/Logs/Components/OlzInfiniteScroll/OlzInfiniteScroll.tsx
- src/Apps/Logs/Components/OlzLogs/OlzLogs.tsx
> Infinite scrolling for logs app

- src/Components/Common/OlzLocationMap/OlzLocationMap.php
- src/News/Endpoints/UpdateNewsEndpoint.php
- src/Termine/Components/OlzTermineList/OlzTermineList.php
- src/Termine/termine.ts
- tests/UnitTests/News/Endpoints/UpdateNewsEndpointTest.php
> Update termine maps to swisstopo

- composer.json
- composer.lock
- src/Apps/Panini2024/Panini2024Controller.php
- src/Apps/Panini2024/Utils/Panini2024Utils.php
> Panini-PDF

- _/profil.php
- src/Apps/Newsletter/Components/OlzEmailCard/OlzEmailCard.php
- src/Components/Auth/OlzAccountMenu/OlzAccountMenu.php
- src/Components/Auth/OlzAccountMenu/OlzAccountMenu.scss
> Verify email for newsletter, fix profile for child accounts

- src/Command/ProcessEmailCommand.php
- tests/screenshot_tests/utils/hideFlaky.js
> Handle bounce email errors

- src/Components/Upload/OlzMultiFileUploader/OlzMultiFileUploader.tsx
- src/Utils/FileUtils.php
- src/Utils/UploadUtils.php
> Fix delete files

- .github/workflows/ci-prod.yml
- .github/workflows/ci-staging.yml
> Migrate to mariadb:latest (v11) again

- _/fuer_einsteiger.php
> Allow fbclid on fuer_einsteiger.php

- src/Termine/Components/OlzTerminDetail/OlzTerminDetail.scss
> Fix scrolling on map

- src/Apps/GoogleSearch/Components/OlzGoogleSearch/OlzGoogleSearch.tsx
- src/Apps/Statistics/Components/OlzStatistics/OlzStatistics.tsx
- src/Apps/Youtube/Components/OlzYoutube/OlzYoutube.tsx
- src/Components/Auth/OlzCopyableCredential/OlzCopyableCredential.tsx
- src/Components/Upload/OlzUploadFile/OlzUploadFile.tsx
> Fix apps screenshots flakiness

- .php_cs_config.php
- src/Command/ProcessEmailCommand.php
- src/Startseite/Components/OlzWeeklyPictureTile/OlzWeeklyPictureTile.php
- src/Utils/EmailUtils.php
- tests/Fake/FakeUserRepository.php
- tests/UnitTests/Command/ProcessEmailCommandTest.php
> Fix email, bild der woche rotation

- src/Termine/Components/OlzICal/OlzICal.php
> Fix long ical events

- src/Components/Common/OlzEntityChooser/OlzEntityChooser.tsx
- src/Components/Common/OlzEntityField/OlzEntityField.tsx
- src/Termine/Components/OlzEditTerminModal/OlzEditTerminModal.tsx
- src/Termine/Components/OlzTermineListItem/OlzTermineListItem.php
> Temine (templates) UX improvements

- src/Components/Common/OlzConfirmationDialog/OlzConfirmationDialog.tsx
- src/Components/Page/OlzFooter/OlzFooter.php
- src/News/Components/OlzNewsDetail/OlzNewsDetail.php
- src/Termine/Components/OlzTerminDetail/OlzTerminDetail.php
> HTTP 401 for unauthorized archive access

- src/Components/OtherPages/OlzTrophy/OlzTrophy.php
- src/Roles/Components/OlzOrganigramm/OlzOrganigramm.php
- src/Roles/Components/OlzOrganigramm/OlzOrganigramm.ts
> Fix horizontal organigramm scroll, deprecate old trophy page

- src/Components/Common/OlzStyles/styles.scss
- src/Controller/NewsController.php
- src/News/Components/OlzNewsDetail/OlzNewsDetail.php
> Implement download all images

- src/Api/Endpoints/ResetPasswordEndpoint.php
> Fix problem with password reset

- src/Command/ProcessEmailCommand.php
> Soft fail fetching emails

- src/Api/Endpoints/ExecuteEmailReactionEndpoint.php
- tests/SystemTests/TermineTest.php
- tests/UnitTests/Api/Endpoints/ExecuteEmailReactionEndpointTest.php
> Fix system test, remove obsolete warning

- src/Entity/SolvEvent.php
> Fix search entities for SOLV events

- src/Command/ProcessEmailCommand.php
- tests/UnitTests/Command/ProcessEmailCommandTest.php
> Fix email to undisclosed recipients
